### ISSUE TITLE
Where to find this file of “7Scenes/img2subscene/chess.pkl”? Thanks!

### ISSUE THREAD

**Issue by dflkasjfh** [AaltoVision/CL_HSCNet#1]
![image](https://user-images.githubusercontent.com/74122454/141307424-d7657315-8629-4e97-8163-b755b5202474.png)

**Comment by dflkasjfh** [comment]
![image](https://user-images.githubusercontent.com/74122454/141393229-cbec35b2-d871-4279-9fbe-f8ec67301361.png)
Hello， this folder， img2subscene ， should be changed location to the upper directory.

**Comment by LZL-CS** [comment]
Hi, 
Can you share the file of the img2subscene link, I can't find it.

Best regards,
