### ISSUE TITLE
7Scenes/img2subscene/heads.pkl

### ISSUE THREAD

**Issue by LZL-CS** [AaltoVision/CL_HSCNet#2]
Hi, may I know where to get '7Scenes/img2subscene/chess.pkl', I can't find it in the project.

**Comment by ffrivera0** [comment]
Now you can find the `img2subscene/` folder under `7Scenes/`

**Comment by ffrivera0** [comment]
> Hi, may I know where to get '7Scenes/img2subscene/chess.pkl', I can't find it in the project.

Now you can find the `img2subscene/` folder under `7Scenes/`
