### ISSUE TITLE
self.split, scene = split.split('_') ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by Chicolor** [AaltoVision/CL_HSCNet#3]
While running the code below

`python eval.py \ --model hscnet \ --dataset i12S \ --scene apt1/kitchen \ --checkpoint /path/to/saved/model/ \ --data_path /path/to/data/`

There will be an error

```
self.split, scene = split.split('_') ValueError: not enough values to unpack (expected 2, got 1)
in CL_HSCNet/blob/main/datasets/twelve_scenes.py
```

From the code I can find at that time "split = test". In that case, what's the meaning of "split.split('_') " ?

By the way, are the models suitable for i12S? The names also begin with i7s.

Sorry to bother you. I would appreciate your help.

**Comment by ffrivera0** [comment]
Thank you for reporting the issue; the bug is fixed now and you can evaluate it on i7S, i12S and i19S

**Comment by ffrivera0** [comment]
> While running the code below
> 
> `python eval.py \ --model hscnet \ --dataset i12S \ --scene apt1/kitchen \ --checkpoint /path/to/saved/model/ \ --data_path /path/to/data/`
> 
> There will be an error
> 
> ```
> self.split, scene = split.split('_') ValueError: not enough values to unpack (expected 2, got 1)
> in CL_HSCNet/blob/main/datasets/twelve_scenes.py
> ```
> 
> From the code I can find at that time "split = test". In that case, what's the meaning of "split.split('_') " ?
> 
> By the way, are the models suitable for i12S? The names also begin with i7s.
> 
> Sorry to bother you. I would appreciate your help.

Thank you for reporting the issue; the bug is fixed now and you can run it on i7S, i12S, and i19S
